name: React-Site-Workflow/Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Echo Building
        run: echo "Building"
        
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Make sure package.json file exists
        run: cat package.json
        
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Deploy to Ec2 Instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          cd sh React-site.sh
          git pull origin
          cd
          sudo cp -r React-Site/* /var/www/html
          sudo systemctl restart nginx